"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['Resources/']
OPTIONS = {
    "iconfile": "icnss.icns",
    "argv_emulation": True,
    "plist": {
        "CFBundleName":
        "KVM Client",  # 应用名
        "CFBundleDisplayName":
        "kvm_client",  # 应用显示名
        "CFBundleVersion":
        "1.0.0",  # 应用版本号
        "CFBundleIdentifier":
        "kvm_client",  # 应用包名、唯一标识
        "NSCameraUsageDescription":
        "Our application needs permission to use camera",
        "NSPhotoLibraryAddUsageDescription":
        "Our application needs permission to write photos",
        "NSHumanReadableCopyright":
        "Copyright © 2023 SW Whztever. All rights reserved."  # 可读版权
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
